### ISSUE TITLE
ㅋㅋㅋㅋㅋ

### ISSUE THREAD

**Issue by Hyeonproject** [linger0310/BigData_Analysis_Final_Exam#2]
![ㅋㅋㅋ](https://user-images.githubusercontent.com/7149932/121382730-db2c2680-c981-11eb-85d8-b8ea5c4f95f1.jpg)

**Comment by linger0310** [comment]
![image](https://mblogthumb-phinf.pstatic.net/MjAxNzA1MTJfMjcy/MDAxNDk0NTcxODYxNjQ5.6OSrjHjgZPooXsnnL_apxRWRcQVBlzd-tB66332mwN8g.163YBSFJoACcukBdRUEs5WTe_MlBE1JBsNX9E34mlU4g.JPEG.nubgood/2017-05-12_15-29-07.jpg?type=w800)
